sudo: required

dist: xenial
language: csharp
mono: none
dotnet: 2.2

before_install:
  - echo "deb https://dl.bintray.com/rabbitmq/debian xenial main" | sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list

install:
  - sudo apt-get install rabbitmq-server
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore

before_script:
  - sudo systemctl start rabbitmq-server
  - export PATH="$PATH:$HOME/.dotnet/tools"

script:
  - dotnet sonarscanner begin /k:"Minor.Nijn" /n:"Minor.Nijn" /o:"dylanvgils-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*,*Example*/**/*" /d:sonar.cs.opencover.reportsPaths="**\*.opencover.xml"
  - dotnet build
  - dotnet test Minor.Nijn.Test/Minor.Nijn.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet test Minor.Nijn.WebScale.Test/Minor.Nijn.WebScale.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet test Minor.Nijn.RabbitMQTest/Minor.Nijn.RabbitMQTest.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet test Examples/ConsoleAppExample.Test/ConsoleAppExample.Test.csproj --no-build
  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'